#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NeuBeacon.Droid.Resource", IsApplication=true)]

namespace NeuBeacon.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int textsize = 2130968576;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int about = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int about_two = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int aboutglow = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int careersglow = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int coin = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int manager = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int manager1 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int manager_sel = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int n_footer = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int n_logo = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int n_splash_logo = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int neucareer = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int neucareer_two = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int quiz = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int quiz_two = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int quizglow = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int sales = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Sales1 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int sales_sel = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int splashscreen = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int tech = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int tech1 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int tech_sel = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int Xamarin_Icon = 2130837528;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07001d
			public const int MyButton = 2131165213;
			
			// aapt resource value: 0x7f07001f
			public const int ProfileHeader = 2131165215;
			
			// aapt resource value: 0x7f070019
			public const int RoleMiddle = 2131165209;
			
			// aapt resource value: 0x7f070015
			public const int ViewProfileHeader = 2131165205;
			
			// aapt resource value: 0x7f070021
			public const int aboutglow = 2131165217;
			
			// aapt resource value: 0x7f070001
			public const int button1 = 2131165185;
			
			// aapt resource value: 0x7f07000d
			public const int button2 = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int button3 = 2131165198;
			
			// aapt resource value: 0x7f070022
			public const int careersglow = 2131165218;
			
			// aapt resource value: 0x7f070005
			public const int child = 2131165189;
			
			// aapt resource value: 0x7f070024
			public const int coinMenuItem = 2131165220;
			
			// aapt resource value: 0x7f070000
			public const int ctlExListBox = 2131165184;
			
			// aapt resource value: 0x7f070017
			public const int email = 2131165207;
			
			// aapt resource value: 0x7f070025
			public const int homeMenuItem = 2131165221;
			
			// aapt resource value: 0x7f070009
			public const int imageAboutNeudesic = 2131165193;
			
			// aapt resource value: 0x7f070003
			public const int imageView1 = 2131165187;
			
			// aapt resource value: 0x7f07000a
			public const int imageViewNeuCareers = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int imageViewQuiz = 2131165195;
			
			// aapt resource value: 0x7f070020
			public const int imagefooter = 2131165216;
			
			// aapt resource value: 0x7f070004
			public const int linearLayout1 = 2131165188;
			
			// aapt resource value: 0x7f07000c
			public const int linearLayout3 = 2131165196;
			
			// aapt resource value: 0x7f07001b
			public const int mindfulmanager = 2131165211;
			
			// aapt resource value: 0x7f070016
			public const int name = 2131165206;
			
			// aapt resource value: 0x7f070014
			public const int navigateMain = 2131165204;
			
			// aapt resource value: 0x7f070018
			public const int phone = 2131165208;
			
			// aapt resource value: 0x7f070023
			public const int quizglow = 2131165219;
			
			// aapt resource value: 0x7f070010
			public const int radioButton1 = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int radioButton2 = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int radioButton3 = 2131165202;
			
			// aapt resource value: 0x7f07000f
			public const int radioGroup1 = 2131165199;
			
			// aapt resource value: 0x7f070007
			public const int relativeLayout1 = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int relativeLayout2 = 2131165192;
			
			// aapt resource value: 0x7f07001c
			public const int salesguy = 2131165212;
			
			// aapt resource value: 0x7f07001e
			public const int splashlogo = 2131165214;
			
			// aapt resource value: 0x7f070013
			public const int splashlogoneu = 2131165203;
			
			// aapt resource value: 0x7f07001a
			public const int techguru = 2131165210;
			
			// aapt resource value: 0x7f070002
			public const int txtLarge = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int txtSmall = 2131165190;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int About = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Career = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Child = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int DataListItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int GroupName = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ListGroup = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int NeucareerChild = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int NeuCareerList = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Profile = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Quiz = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Welcome = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int menus = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int app_label = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int beacon_notification = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
