#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MySecurity.Resource", IsApplication=true)]

namespace MySecurity
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int alert = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bell = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int call = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int cross1 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int msg4 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int tick2 = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int Start_ALarm = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int Stop_ALarm = 2131099649;
			
			// aapt resource value: 0x7f06000a
			public const int TableGPS = 2131099658;
			
			// aapt resource value: 0x7f06000d
			public const int button1 = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int button2 = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int button3 = 2131099663;
			
			// aapt resource value: 0x7f060002
			public const int cancelButton = 2131099650;
			
			// aapt resource value: 0x7f060010
			public const int contact = 2131099664;
			
			// aapt resource value: 0x7f060004
			public const int contacts = 2131099652;
			
			// aapt resource value: 0x7f060009
			public const int mediaController1 = 2131099657;
			
			// aapt resource value: 0x7f060006
			public const int name1 = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int name2 = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int relativeLayout1 = 2131099659;
			
			// aapt resource value: 0x7f060003
			public const int saveButton = 2131099651;
			
			// aapt resource value: 0x7f06000c
			public const int tableRow10 = 2131099660;
			
			// aapt resource value: 0x7f060005
			public const int tableRow11 = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int tableRow12 = 2131099655;
			
			// aapt resource value: 0x7f060012
			public const int textView3 = 2131099666;
			
			// aapt resource value: 0x7f060014
			public const int textView4 = 2131099668;
			
			// aapt resource value: 0x7f060011
			public const int txtDateTimeAndProvider = 2131099665;
			
			// aapt resource value: 0x7f060013
			public const int txtLatitude = 2131099667;
			
			// aapt resource value: 0x7f060015
			public const int txtLongitude = 2131099669;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int alarm = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int contacts = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int police_alarm = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int cancelButton = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int saveButton = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int txt_latitude = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int txt_longitude = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
