#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NeuBeacon.Droid.Resource", IsApplication=true)]

namespace NeuBeacon.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int about = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int about_two = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int aboutglow = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int careersglow = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int check = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int coin = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int manager = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int manager1 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int manager_sel = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int n_footer = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int n_logo = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int n_splash_logo = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Neu_Career_select = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Neu_logo = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int neucareer = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int neucareer_two = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int quiz = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int quiz_two = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int quizglow = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int sales = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Sales1 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int sales_sel = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int splashscreen = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int tech = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int tech1 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int tech_sel = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int Xamarin_Icon = 2130837531;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060024
			public const int MyButton = 2131099684;
			
			// aapt resource value: 0x7f060026
			public const int ProfileHeader = 2131099686;
			
			// aapt resource value: 0x7f060019
			public const int RoleMiddle = 2131099673;
			
			// aapt resource value: 0x7f060015
			public const int ViewProfileHeader = 2131099669;
			
			// aapt resource value: 0x7f060028
			public const int aboutglow = 2131099688;
			
			// aapt resource value: 0x7f060023
			public const int answer = 2131099683;
			
			// aapt resource value: 0x7f06000c
			public const int button1 = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int button2 = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int button3 = 2131099662;
			
			// aapt resource value: 0x7f060029
			public const int careersglow = 2131099689;
			
			// aapt resource value: 0x7f060004
			public const int child = 2131099652;
			
			// aapt resource value: 0x7f06002b
			public const int coinMenuItem = 2131099691;
			
			// aapt resource value: 0x7f060000
			public const int ctlExListBox = 2131099648;
			
			// aapt resource value: 0x7f060017
			public const int email = 2131099671;
			
			// aapt resource value: 0x7f06002c
			public const int homeMenuItem = 2131099692;
			
			// aapt resource value: 0x7f06001d
			public const int icon = 2131099677;
			
			// aapt resource value: 0x7f060008
			public const int imageAboutNeudesic = 2131099656;
			
			// aapt resource value: 0x7f060002
			public const int imageView1 = 2131099650;
			
			// aapt resource value: 0x7f060009
			public const int imageViewNeuCareers = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int imageViewQuiz = 2131099658;
			
			// aapt resource value: 0x7f060027
			public const int imagefooter = 2131099687;
			
			// aapt resource value: 0x7f060003
			public const int linearLayout1 = 2131099651;
			
			// aapt resource value: 0x7f06000b
			public const int linearLayout3 = 2131099659;
			
			// aapt resource value: 0x7f06001b
			public const int mindfulmanager = 2131099675;
			
			// aapt resource value: 0x7f060016
			public const int name = 2131099670;
			
			// aapt resource value: 0x7f06001f
			public const int option1 = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int option2 = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int option3 = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int option4 = 2131099682;
			
			// aapt resource value: 0x7f060018
			public const int phone = 2131099672;
			
			// aapt resource value: 0x7f06001e
			public const int question = 2131099678;
			
			// aapt resource value: 0x7f06002a
			public const int quizglow = 2131099690;
			
			// aapt resource value: 0x7f060010
			public const int radioButton1 = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int radioButton2 = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int radioButton3 = 2131099666;
			
			// aapt resource value: 0x7f06000f
			public const int radioGroup1 = 2131099663;
			
			// aapt resource value: 0x7f060006
			public const int relativeLayout1 = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int relativeLayout2 = 2131099655;
			
			// aapt resource value: 0x7f06001c
			public const int salesguy = 2131099676;
			
			// aapt resource value: 0x7f060025
			public const int splashlogo = 2131099685;
			
			// aapt resource value: 0x7f060013
			public const int splashlogoneu = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int sru = 2131099668;
			
			// aapt resource value: 0x7f06001a
			public const int techguru = 2131099674;
			
			// aapt resource value: 0x7f060001
			public const int txtLarge = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int txtSmall = 2131099653;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int About = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Career = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Child = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int DataListItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int GroupName = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ListGroup = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int NeucareerChild = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int NeuCareerList = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Profile = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Quiz = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int QuizQuestionChild = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Welcome = 2130903052;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int menus = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int app_label = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int beacon_notification = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
